import pygame

tiles = {
		"empty": pygame.image.load("misc/empty.png").convert_alpha(),
		"fond": pygame.image.load("misc/fond.jpg").convert(),
		"grid": pygame.image.load("misc/grid.png").convert_alpha(),
		"perso": pygame.image.load("misc/perso.png").convert_alpha(),
		"stone": pygame.image.load("stones/stone.png").convert(),
		"top_stone": pygame.image.load("stones/top_stone.png").convert(),
		"half_stone": pygame.image.load("stones/half_stone.png").convert(),
		"half_top_stone": pygame.image.load("stones/half_top_stone.png").convert(),
		"stone_under_slope_up": pygame.image.load("stones/stone_under_slope_up.png").convert(),
		"stone_under_slope_down": pygame.image.load("stones/stone_under_slope_down.png").convert(),
		"half_stone_under_slope_up": pygame.image.load("stones/half_stone_under_slope_up.png").convert(),
		"half_stone_under_slope_down": pygame.image.load("stones/half_stone_under_slope_down.png").convert(),
		"stone_slope_up": pygame.image.load("stones/stone_slope_up.png").convert_alpha(),
		"stone_slope_down": pygame.image.load("stones/stone_slope_down.png").convert_alpha(),
		"top_stone_slope_up": pygame.image.load("stones/top_stone_slope_up.png").convert_alpha(),
		"top_stone_slope_down": pygame.image.load("stones/top_stone_slope_down.png").convert_alpha(),
		"half_stone_slope_up": pygame.image.load("stones/half_stone_slope_up.png").convert_alpha(),
		"half_stone_slope_down": pygame.image.load("stones/half_stone_slope_down.png").convert_alpha(),
		"half_top_stone_slope_up": pygame.image.load("stones/half_top_stone_slope_up.png").convert_alpha(),
		"half_top_stone_slope_down": pygame.image.load("stones/half_top_stone_slope_down.png").convert_alpha(),
		"stone_brick": pygame.image.load("stones/stone_brick.png").convert_alpha(),
		"dirt": pygame.image.load("dirt/dirt.png").convert(),
		"top_dirt": pygame.image.load("dirt/top_dirt.png").convert(),
		"half_dirt": pygame.image.load("dirt/half_dirt.png").convert(),
		"half_top_dirt": pygame.image.load("dirt/half_top_dirt.png").convert(),
		"dirt_under_slope_up": pygame.image.load("dirt/dirt_under_slope_up.png").convert(),
		"dirt_under_slope_down": pygame.image.load("dirt/dirt_under_slope_down.png").convert(),
		"half_dirt_under_slope_up": pygame.image.load("dirt/half_dirt_under_slope_up.png").convert(),
		"half_dirt_under_slope_down": pygame.image.load("dirt/half_dirt_under_slope_down.png").convert(),
		"dirt_slope_up": pygame.image.load("dirt/dirt_slope_up.png").convert_alpha(),
		"dirt_slope_down": pygame.image.load("dirt/dirt_slope_down.png").convert_alpha(),
		"top_dirt_slope_up": pygame.image.load("dirt/top_dirt_slope_up.png").convert_alpha(),
		"top_dirt_slope_down": pygame.image.load("dirt/top_dirt_slope_down.png").convert_alpha(),
		"half_dirt_slope_up": pygame.image.load("dirt/half_dirt_slope_up.png").convert_alpha(),
		"half_dirt_slope_down": pygame.image.load("dirt/half_dirt_slope_down.png").convert_alpha(),
		"half_top_dirt_slope_up": pygame.image.load("dirt/half_top_dirt_slope_up.png").convert_alpha(),
		"half_top_dirt_slope_down": pygame.image.load("dirt/half_top_dirt_slope_down.png").convert_alpha(),
		"spikes": pygame.image.load("misc/spikes.png").convert_alpha(),
		"water": pygame.image.load("misc/water.png").convert_alpha(),
		"water_waves": pygame.image.load("misc/water_waves.png").convert_alpha(),
		"underwater": pygame.image.load("misc/underwater.png").convert(),
		"lava": pygame.image.load("misc/lava.png").convert_alpha(),
		"lava_waves": pygame.image.load("misc/lava_waves.png").convert_alpha(),
		"underlava": pygame.image.load("misc/underlava.png").convert(),
		"spawn_flag": pygame.image.load("misc/spawn_flag.png").convert_alpha(),
		"end_flag": pygame.image.load("misc/end_flag.png").convert_alpha()
		}

tags = {
		"empty": [],
		"stone": ["solid", "align_tl"],
		"top_stone": ["solid", "align_tl"],
		"half_stone": ["solid", "align_bl"],
		"half_top_stone": ["solid", "align_bl"],
		"stone_under_slope_up": ["solid", "align_tl"],
		"stone_under_slope_down": ["solid", "align_tl"],
		"half_stone_under_slope_up": ["solid", "align_bl"],
		"half_stone_under_slope_down": ["solid", "align_bl"],
		"stone_slope_up": ["slope_up", "align_bl"],
		"stone_slope_down": ["slope_down", "align_bl"],
		"top_stone_slope_up": ["slope_up", "align_bl"],
		"top_stone_slope_down": ["slope_down", "align_bl"],
		"half_stone_slope_up": ["slope_up", "align_bl"],
		"half_stone_slope_down": ["slope_down", "align_bl"],
		"half_top_stone_slope_up": ["slope_up", "align_bl"],
		"half_top_stone_slope_down": ["slope_down", "align_bl"],
		"stone_brick": ["solid", "align_tl"],
		"dirt": ["solid", "align_tl"],
		"top_dirt": ["solid", "align_tl"],
		"half_dirt": ["solid", "align_bl"],
		"half_top_dirt": ["solid", "align_bl"],
		"dirt_under_slope_up": ["solid", "align_tl"],
		"dirt_under_slope_down": ["solid", "align_tl"],
		"half_dirt_under_slope_up": ["solid", "align_bl"],
		"half_dirt_under_slope_down": ["solid", "align_bl"],
		"dirt_slope_up": ["slope_up", "align_bl"],
		"dirt_slope_down": ["slope_down", "align_bl"],
		"top_dirt_slope_up": ["slope_up", "align_bl"],
		"top_dirt_slope_down": ["slope_down", "align_bl"],
		"half_dirt_slope_up": ["slope_up", "align_bl"],
		"half_dirt_slope_down": ["slope_down", "align_bl"],
		"half_top_dirt_slope_up": ["slope_up", "align_bl"],
		"half_top_dirt_slope_down": ["slope_down", "align_bl"],
		"spikes": ["mortal", "align_bl"],
		"water": ["mortal", "align_bl"],
		"water_waves": ["mortal", "align_bl"],
		"underwater": ["mortal", "align_tl"],
		"lava": ["mortal", "align_bl"],
		"lava_waves": ["mortal", "align_bl"],
		"underlava": ["mortal", "align_tl"],
		"spawn_flag": ["deco", "align_mt"],
		"end_flag": ["deco", "align_mt"]
		}